### ISSUE TITLE
Create STL file

### ISSUE THREAD

**Issue by eladbd** [Ido-Cohen/TheUnseenView#10]

**Comment by Ido-Cohen** [comment]
we managed to create the desired STL file but we running few problems:
1. the file is too heavy(~230MB) - and takes time for slicer software to handle it, minor problem, we will keep it like that in order to keep the printed image in high quality.
2. the run time of generating the file in Python is slow, we considering using Java instead, we already made a working Java component, which is 10 times faster.
![image](https://user-images.githubusercontent.com/61789416/236201364-7dfef007-24e1-439b-a076-c8982ac18772.png)

**Comment by Ido-Cohen** [comment]
We decided to keep it with Python, we were able to achieve better results - the STL file was more printable.
We ran into a lot of problems on the way, the meshes had holes, especially in the sides, and as a result, the file was unprintable.
We solved these problems through a lot of trial and error.
