### ISSUE TITLE
Image processing - Add Braile legend at the bottom

### ISSUE THREAD

**Issue by eladbd** [Ido-Cohen/TheUnseenView#9]

**Comment by Ido-Cohen** [comment]
Since the AI model we are using has a fixed vocabulary of objects it recognizes we decided to translate this vocabulary into braille and draw it on images once and add the required image if necessary.
This way we will shorten the running times a little.
We have included the component that converts the text into words under the name: TextDrawer.py.

**Comment by Ido-Cohen** [comment]
next, we need to make a component that inserts these images into the processed image bottom with the related pattern next to it.
![image](https://user-images.githubusercontent.com/61789416/236202822-6842b752-8144-4bbc-9992-79a932f4aa42.png)

**Comment by Ido-Cohen** [comment]
We decided to change the background color to gray in order to reduce the height of the legend from the base so that the structure of the printed image will be more robust and the braille will be more legible.
We also had to increase the braille font size to meet the braille standard.
![banner](https://github.com/Ido-Cohen/TheUnseenView/assets/61789416/975677be-3a0f-4f1b-9c9a-338c0bf17da7)
